# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
