# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170128_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='classRoom',
            new_name='class_room',
        ),
    ]
