# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170207_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ClientProfile')),
            ],
        ),
    ]
