# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_classhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='day',
        ),
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='dimanche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='class',
            name='jeudi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='lundi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='mardi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='mercredi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='samedi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='class',
            name='vendredi',
            field=models.BooleanField(default=False),
        ),
    ]
