# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170218_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
