# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 17:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170614_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.CharField(default=datetime.datetime(2017, 6, 14, 17, 25, 48, 699147, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.CharField(default=datetime.datetime(2017, 6, 14, 17, 26, 3, 951222, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
