# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20170614_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='dimanche',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='jeudi',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='lundi',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='mardi',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='mercredi',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='samedi',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='vendredi',
            new_name='wednesday',
        ),
    ]
